### ISSUE TITLE
Is there a demo for this? XD

### ISSUE THREAD

**Issue by zzz6519003** [kevinchau321/FullScreenSuperMarioWorld#1]

**Comment by kevin-chau** [comment]
Hi @zzz6519003 
I literally just started this last night. Nothing from super mario world has been ported into this engine yet, but everything from super mario bros works fine. Just clone the repo, open up /FullScreenMario/Source/index.html in your browser and you should be able to play the whole super mario bros game. Thanks.

**Comment by kevin-chau** [comment]
@zzz6519003 
Started a new repository for this project. This time it has a working demo, check it out!
https://github.com/kevinchau321/SuperMarioWorldJS

**Comment by zzz6519003** [comment]
wow! man ur just awesome! i'm learning piano using The One®

**Comment by zzz6519003** [comment]
but GFWed...
gosh i wanna fly!

**Comment by zzz6519003** [comment]
i'm sure u know u can use issues as a TODO list XD 
because gist is GFWed...
